import type { Metadata } from "next";
import "../styles/customBootstrap.css";
import Navbar from "./components/Navbar";
import { Montserrat, Public_Sans } from "next/font/google";
import Footer from "./components/Footer";
import { cookies } from "next/headers"; // For server-side cookie access

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-public-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const savedMode = (await cookieStore).get("darkMode");
  const initialDarkMode = savedMode ? JSON.parse(savedMode.value) : false;
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${publicSans.variable} ${
        initialDarkMode ? "dark" : ""
      }`}
    >
      <body className="bg-background public-sans">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
